version: "3.9"

services:
  portfolio-frontend:
    build:
      context: ../../../
      dockerfile: Dockerfile
    image: portfolio-frontend:latest
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`portfolio.raunit.dpdns.org`)"
      - "traefik.http.routers.portfolio.entrypoints=web"

  portfolio-backend:
    build:
      context: ../../../
      dockerfile: Dockerfile.backend
    image: portfolio-backend:latest
    restart: unless-stopped
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - PORT=5000
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio-api.rule=Host(`portfolio.raunit.dpdns.org`) && PathPrefix(`/api`)"
      - "traefik.http.routers.portfolio-api.entrypoints=web"
      - "traefik.http.services.portfolio-api.loadbalancer.server.port=5000"

networks:
  proxy:
    external: true