version: "3.9"

services:
  portfolio:
    image: portfolio
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`portfolio.raunit.dpdns.org`)"
      - "traefik.http.routers.portfolio.entrypoints=web"

networks:
  proxy:
    external: true
